### ISSUE TITLE
pyapns doesn't work with Twisted v17.1.0

### ISSUE THREAD

**Issue by sachinrekhi** [samuraisam/pyapns#83]
I just upgraded to the latest version of Twisted, v17.1.0, and pyapns stopped working. You get the following error:

```
Traceback (most recent call last):
  File "/notejoy/env/bin/twistd", line 9, in <module>
    load_entry_point('Twisted==17.1.0', 'console_scripts', 'twistd')()
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
    app.run(runApp, ServerOptions)
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/application/app.py", line 662, in run
    runApp(config)
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/application/app.py", line 380, in run
    self.application = self.createOrGetApplication()
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/application/app.py", line 440, in createOrGetApplication
    ser = plg.makeService(self.config.subOptions)
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/web/tap.py", line 254, in makeService
    strports.service(config['port'], site).setServiceParent(s)
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/application/strports.py", line 40, in service
    endpoints.serverFromString(reactor, description), factory)
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1569, in serverFromString
    nameOrPlugin, args, kw = _parseServer(description, None)
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1487, in _parseServer
    getPlugins(IStreamServerEndpointStringParser), endpointType
  File "/notejoy/env/local/lib64/python2.7/site-packages/twisted/internet/endpoints.py", line 1503, in _matchPluginToPrefix
    raise ValueError("Unknown endpoint type: '%s'" % (endpointType,))
ValueError: Unknown endpoint type: '7077'
```

Once I downgraded Twisted to v16.1.1, pyapns started working again with no changes.

**Comment by samuraisam** [comment]
Accepting pull requests!

**Comment by mark-anders** [comment]
I had posted this to another issue but am moving it here, since this fixes the error shown.

Twisted changed the command line syntax. Use `--port tcp:port=7077`.   I just tried this with  twistd 18.9.0 and it works.
